### PR TITLE
Bump z-schema library to fix PRISMA-2021-0063.

### PR DESCRIPTION
**Pull request by abdulgit2021**

### CODE REVIEW

**Comment by sikmir** [comment]
Duplicates #166

**Review by philsturgeon — APPROVED** [review]

**Comment by abdulgit2021** [comment]
@philsturgeon can you please publish the latest version. thanks!

**Comment by philsturgeon** [comment]
Yes, everyone who sent a pull request has asked me to do this since I merged them. There's a meme about this. :D 

When main is passing tests I'll be happy to tag a version.

**Comment by sukusukumar** [comment]
@philsturgeon can you please tag this change to a new version

**Comment by philsturgeon** [comment]
Just waiting on https://github.com/APIDevTools/swagger-parser/pull/175. Can't tag things with CI Failing as I said.

**Pull request merged**
