### PR TITLE
Spec inconsistancy checks work on OpenAPI v3.0 specs as well

### PR DESCRIPTION
**Pull request by stueynz**
Now performs the same inconstancy checks in OpenAPI v3.0 that are detected in Swagger v2.0 specs.
We could of course add more inconstancy checks - but another time.

### CODE REVIEW

**Comment by stueynz** [comment]
@philsturgeon Any chance of a review?

**Comment by philsturgeon** [comment]
Sorry to do this @P0lip but can I put this on your radar too?

**Comment by philsturgeon** [comment]
@stueynz hey, sorry for the delay and the conflicts, but we just tagged v10.0.3 and I'd like to get this in next. Can you update it and make sure tests are passing ok?

**Comment by stueynz** [comment]
@philsturgeon   onto it ... later in the week.

**Comment by clarencedesmarais** [comment]
Any updates on this one ?

**Comment by stueynz** [comment]
Decided the easiest thing to do was  - start again with top-of main branch.  So close this PR in deference to [new PR 198](https://github.com/APIDevTools/swagger-parser/pull/198)

**Comment by stueynz** [comment]
> Any updates on this one ? This feature would be quite useful :)



> Any updates on this one ? This feature would be quite useful :)

Please see [replacement PR](https://github.com/APIDevTools/swagger-parser/pull/198)

**Pull request closed without merging**
